# Generated by Django 5.0.3 on 2024-06-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='added_by',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
