# Generated by Django 5.0.3 on 2024-06-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='added_by',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
