# Generated by Django 5.0.3 on 2024-06-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
