# Generated by Django 5.0.3 on 2024-06-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='added_by',
            field=models.CharField(max_length=150),
        ),
    ]
